FROM python:3.9
WORKDIR /app
COPY . .
RUN pip install django
RUN pip install djangorestframework
RUN pip install Crypto
RUN pip install pycryptodome
RUN pip install django-cors-headers
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
